### ISSUE TITLE
dead links on the readme

### ISSUE THREAD

**Issue by omarcostahamido** [kendallstrautman/quercus-blocks#24]
"Inline Blocks & GitHub Open Authoring."
are 404.

O

**Comment by DirtyF** [comment]
@omarcostahamido Thanks, we just moved some things around on https://tinacms.orrg documentation. We'll add proper redirects.Here are the new links:

- https://tinacms.org/docs/ui/inline-editing/inline-blocks/
- https://tinacms.org/guides/nextjs/github/initial-setup/
